CREATE TABLE KH_STUDENT (
    STD_NO NUMBER PRIMARY KEY,
    STD_NAME NVARCHAR2(5) NOT NULL,
    STD_AGE NUMBER NOT NULL,
    MAJOR NVARCHAR2(10) NOT NULL,
    ENT_DATE DATE DEFAULT SYSDATE
);

-- PK 값 자동 증가용 시퀀스로 만들어

CREATE SEQUENCE SEQ_STD_NO NOCACHE;
